on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release APK"

jobs:
  build:
    name: Build & Release APK
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get Flutter Packages
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          # Adjust the artifact path if needed (this pattern matches all APKs built)
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}


